name: first_task1

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  first_task1:
    runs-on: ubuntu-latest

    steps:
      - name: Saluda a todos
        run: echo "Welcome a todos"

      - name: FechaSistema
        run: |
          echo "Bienvenidos a primer desafio"
          echo "Donde fue creado mi primer WorkFlow"
          echo "Gracias a Dios"
          date