#Jose Andres Gutierrez Vargas
name: Hello World in the Workflow
on: 
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Say hello
        run: echo "Hello world"

      - name: Fecha
        run: date

      - name: Info del sistema
        run: uname -a